### ISSUE TITLE
Change __resource.lua to fxmanifest.lua

### ISSUE THREAD

**Issue by MichaelCoding25** [JaredScar/BadgerFires#1]
__resource is severely outdated in fivem and fxmanifest is a much newer and better version that allows the use of many more natives than the __resource versions did.

Explanation:
[https://docs.fivem.net/docs/scripting-reference/resource-manifest/resource-manifest/](https://docs.fivem.net/docs/scripting-reference/resource-manifest/resource-manifest/)

**Comment by JaredScar** [comment]
I mean if someone pull requests it and adds it, I'll do it, but other than that it's not really needed considering the script works with the natives involved already.
